"""update for claim details types

Revision ID: b27c22175807
Revises: aa71560a3d36
Create Date: 2026-03-22 13:22:54.192647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b27c22175807'
down_revision: Union[str, Sequence[str], None] = 'aa71560a3d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('insurance_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('date_of_accident', sa.String(length=20), nullable=True))
    op.add_column('claims', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('claims', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('claims', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('claims', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('claims', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'claims', 'insurance_policies', ['insurance_id'], ['id'])
    op.drop_column('claims', 'location_lat')
    op.drop_column('claims', 'date_created')
    op.drop_column('claims', 'location_lng')
    op.add_column('drivers', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('license_issued_date', sa.String(length=20), nullable=True))
    op.add_column('drivers', sa.Column('address', sa.String(length=255), nullable=True))
    op.drop_column('drivers', 'name')
    op.add_column('insurance_policies', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('insurance_policies', sa.Column('start_date', sa.String(length=20), nullable=True))
    op.add_column('insurance_policies', sa.Column('end_date', sa.String(length=20), nullable=True))
    op.add_column('insurance_policies', sa.Column('coverage_type', sa.String(length=100), nullable=True))
    op.drop_column('insurance_policies', 'provider')
    op.add_column('vehicles', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('vin', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('color', sa.String(length=50), nullable=True))
    op.drop_column('vehicles', 'license_plate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('license_plate', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('vehicles', 'color')
    op.drop_column('vehicles', 'vin')
    op.drop_column('vehicles', 'registration_number')
    op.add_column('insurance_policies', sa.Column('provider', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('insurance_policies', 'coverage_type')
    op.drop_column('insurance_policies', 'end_date')
    op.drop_column('insurance_policies', 'start_date')
    op.drop_column('insurance_policies', 'company')
    op.add_column('drivers', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'license_issued_date')
    op.drop_column('drivers', 'license_number')
    op.drop_column('drivers', 'date_of_birth')
    op.drop_column('drivers', 'last_name')
    op.drop_column('drivers', 'first_name')
    op.add_column('claims', sa.Column('location_lng', mysql.FLOAT(), nullable=True))
    op.add_column('claims', sa.Column('date_created', mysql.DATETIME(), nullable=True))
    op.add_column('claims', sa.Column('location_lat', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'gps_longitude')
    op.drop_column('claims', 'gps_latitude')
    op.drop_column('claims', 'image_url')
    op.drop_column('claims', 'audio_url')
    op.drop_column('claims', 'location')
    op.drop_column('claims', 'date_of_accident')
    op.drop_column('claims', 'insurance_id')
    # ### end Alembic commands ###
